# примеры API-запросов

@baseUrl = http://localhost:8001/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Authorization: Token 36b94c7d4523f29c70164d59a8949f7ec98ff3ed
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 58d1a902d3fb07df580c9dd80e68c41aa6a05c3a
# 36b94c7d4523f29c70164d59a8949f7ec98ff3ed

{
  "title": "Шкаф IKEA",
  "description": "Срочно"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/8/
Content-Type: application/json
Authorization: Token 58d1a902d3fb07df580c9dd80e68c41aa6a05c3a

{
  "status": "DRAFT"
}

###

DELETE {{baseUrl}}/advertisements/6/
Content-Type: application/json
Authorization: Token 58d1a902d3fb07df580c9dd80e68c41aa6a05c3a

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=2
Authorization: Token 58d1a902d3fb07df580c9dd80e68c41aa6a05c3a
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2024-05-03
Authorization: Token 58d1a902d3fb07df580c9dd80e68c41aa6a05c3a
Content-Type: application/json
###

# фильтрация по статусу
GET {{baseUrl}}/advertisements/?status=DRAFT
Authorization: Token 58d1a902d3fb07df580c9dd80e68c41aa6a05c3a
Content-Type: application/json